# used only for dev, localhost:8080

version: '3.8'

services:
  astrowind:
    container_name: astrowind
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./apps/astrowind/docker/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - proxy

networks:
  proxy:
    external: true
