version: '3'

services:
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: ./apps/blog/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
